const TYPES=["과학의 기본량","측정 표준과 정보","우주의 시작과 원소의 생성","지구와 생명체를 구성하는 원소의 생성","원소의 규칙성","화학 결합과 물질의 성질","지각과 생명체 구성 물질의 규칙성","물질의 전기적 성질","지구 시스템의 구성과 상호 작용","지권의 변화와 영향","중력의 작용","운동과 충돌","생명 시스템과 세포","생명 시스템에서 일어나는 화학 반응","생명 시스템에서 정보의 흐름","지질 시대의 환경과 생물 변화","진화와 생물 다양성","산화와 환원","산, 염기와 중화 반응","물질 변화에서 에너지의 출입","생태계 구성과 환경","생태계 평형","지구 환경 변화와 인간 생활","태양에너지의 생성과 전환","전기 에너지의 생산","에너지 효율과 신재생 에너지","과학 기술의 활용","과학 기술의 발전과 쟁점"];
const DIFFICULTIES=["하","중","상","최상"],ANSWERS=["","①","②","③","④","⑤"],STATEMENTS=["ㄱ","ㄴ","ㄷ","ㄱ ㄴ","ㄱ ㄷ","ㄴ ㄷ","ㄱ ㄴ ㄷ"],QUICK_SLOTS=36;
const STORE_KEY="mock-note-state-v1",CONFIG_KEY="mock-note-config-v1",CURRENT_YEAR=new Date().getFullYear();
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const esc=value=>String(value??"").replace(/[&<>"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
const clean=value=>String(value||"").replace(/\s+/g," ").trim();
const now=()=>new Date().toISOString();
const uid=()=>`Q-${Date.now().toString(36).toUpperCase()}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36).toUpperCase()}`;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let state=loadState(),imageDraft=null,imageRemoved=false,currentPage="record",detailId="",toastTimer,quickExams=[],quickCompareMode="number",recordCompareMode="type",syncInFlight=null,syncQueuedPush=false;

function defaultQuick(){return{answers:Array(QUICK_SLOTS).fill(null),statements:Array(QUICK_SLOTS).fill(""),types:Array(QUICK_SLOTS).fill("")};}
function normalizeQuick(input={}){return{answers:Array.from({length:QUICK_SLOTS},(_,i)=>{const value=Number(input.answers?.[i]);return value>=1&&value<=5?value:null}),statements:Array.from({length:QUICK_SLOTS},(_,i)=>STATEMENTS.includes(input.statements?.[i])?input.statements[i]:""),types:Array.from({length:QUICK_SLOTS},(_,i)=>TYPES.includes(input.types?.[i])?input.types[i]:"")};}
function normalizeQuestion(q={}){const examTitle=clean(q.examTitle||q.season);return{...q,examTitle,season:examTitle,subject:q.subject||"통합과학",year:String(q.year||CURRENT_YEAR),round:Number(q.round)||1,number:Number(q.number)||1,type:TYPES.includes(q.type)?q.type:clean(q.type),detailType:clean(q.detailType),difficulty:DIFFICULTIES.includes(q.difficulty)?q.difficulty:"중",score:Number(q.score)||2,answer:q.answer||"",explanationHtml:q.explanationHtml||"",explanationText:q.explanationText||"",memo:String(q.memo||""),imageFileId:q.imageFileId||"",imageFileName:q.imageFileName||"",imageUrl:q.imageUrl||"",hasLocalImage:Boolean(q.hasLocalImage),createdAt:q.createdAt||now(),updatedAt:q.updatedAt||q.createdAt||now()};}
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORE_KEY));if(saved&&Array.isArray(saved.questions)){const questions=saved.questions.map(normalizeQuestion),selected=(Array.isArray(saved.selectedExams)?saved.selectedExams:[]).map(value=>questions.find(q=>examKey(q)===value)||questions.find(q=>q.examTitle===value)).filter(Boolean).map(examKey);return{...saved,questions,seasons:Array.isArray(saved.seasons)?saved.seasons:[],quick:normalizeQuick(saved.quick),selectedExams:[...new Set(selected)].slice(0,8),dirty:Boolean(saved.dirty)};}}catch{}return{questions:[],seasons:[],quick:defaultQuick(),selectedExams:[],updatedAt:null,dirty:false};}
function persist(dirty=true){state.dirty=dirty||state.dirty;state.updatedAt=now();localStorage.setItem(STORE_KEY,JSON.stringify(state));setSaveState();}
function config(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY))||{};}catch{return{};}}
function options(element,items,value,placeholder){element.innerHTML=(placeholder?`<option value="">${esc(placeholder)}</option>`:"")+items.map(item=>`<option value="${esc(item)}" ${String(item)===String(value)?"selected":""}>${esc(item)}</option>`).join("");}
function examKey(q){return[clean(q.subject)||"통합과학",String(q.year||CURRENT_YEAR),clean(q.examTitle||q.season),Number(q.round)||1].join("\u241f");}
function examLabel(q){return`${q.subject||"통합과학"} · ${q.year||CURRENT_YEAR} · ${q.examTitle||q.season||"제목 없음"} · ${Number(q.round)||1}회`;}
function examCatalog(){const map=new Map();state.questions.forEach(q=>{if(q.examTitle&&!map.has(examKey(q)))map.set(examKey(q),q)});return[...map.entries()].map(([key,q])=>({key,label:examLabel(q),question:q})).sort((a,b)=>a.label.localeCompare(b.label,"ko",{numeric:true}));}
function setExamOptions(element,items,value,placeholder){element.innerHTML=`<option value="">${placeholder}</option>`+items.map(item=>`<option value="${esc(item.key)}" ${item.key===value?"selected":""}>${esc(item.label)}</option>`).join("");}
function difficultyClass(value){return{"하":"low","중":"mid","상":"high","최상":"top"}[value]||"mid";}
function answerNumber(value){const index=ANSWERS.indexOf(value);return index>0?index:Number(value)||0;}
function format(value){return Number.isInteger(Number(value))?String(Number(value)):Number(value).toFixed(1);}
function showToast(message,error=false){const toast=$("#toast");toast.textContent=message;toast.style.background=error?"#a83249":"";toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2400);}
function setSaveState(text){$("#saveState").textContent=text||(state.dirty?"동기화할 변경 있음":state.updatedAt?`최근 저장 ${new Date(state.updatedAt).toLocaleString("ko-KR")}`:"로컬 준비됨");}
function setBusy(button,busy,label){button.disabled=busy;if(busy){button.dataset.label=button.textContent;button.textContent=label||"처리 중…";}else if(button.dataset.label){button.textContent=button.dataset.label;delete button.dataset.label;}}

async function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open("mock-note-images",1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains("drafts"))request.result.createObjectStore("drafts")};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});}
async function dbSet(key,value){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction("drafts","readwrite");tx.objectStore("drafts").put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});}
async function dbGet(key){const db=await openDb();return new Promise((resolve,reject)=>{const request=db.transaction("drafts").objectStore("drafts").get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});}
async function dbDelete(key){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction("drafts","readwrite");tx.objectStore("drafts").delete(key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});}
async function collectDrafts(){const db=await openDb();return new Promise((resolve,reject)=>{const request=db.transaction("drafts").objectStore("drafts").getAllKeys();request.onsuccess=async()=>{const result={};for(const key of request.result){const value=await dbGet(key);if(value)result[key]=value;}resolve(result)};request.onerror=()=>reject(request.error)});}

function sanitizePastedHtml(html,text){if(!html)return esc(text).replace(/\r?\n/g,"<br>");const doc=new DOMParser().parseFromString(html,"text/html"),allowed=new Set(["BR","P","DIV","SUP","SUB","B","STRONG","I","EM","U"]);function cleanNode(node){if(node.nodeType===Node.TEXT_NODE)return document.createTextNode(node.textContent);if(node.nodeType!==Node.ELEMENT_NODE)return document.createDocumentFragment();const vertical=(node.style?.verticalAlign||"").toLowerCase();let output;if(node.tagName==="SUP"||vertical.includes("super"))output=document.createElement("sup");else if(node.tagName==="SUB"||vertical.includes("sub"))output=document.createElement("sub");else if(allowed.has(node.tagName))output=document.createElement(node.tagName.toLowerCase());else output=document.createDocumentFragment();[...node.childNodes].forEach(child=>output.appendChild(cleanNode(child)));return output;}const box=document.createElement("div");[...doc.body.childNodes].forEach(child=>box.appendChild(cleanNode(child)));return box.innerHTML;}
function insertHtmlAtCursor(html){document.execCommand("insertHTML",false,html);}
async function compressImage(file){const bitmap=await createImageBitmap(file),max=1900,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d",{alpha:false}).drawImage(bitmap,0,0,canvas.width,canvas.height);let quality=.9,blob;do{blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/webp",quality));quality-=.08;}while(blob&&blob.size>950000&&quality>.55);const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)});return{dataUrl,mimeType:blob.type,size:blob.size,width:canvas.width,height:canvas.height};}
async function acceptImage(file){if(!file?.type.startsWith("image/"))return showToast("이미지 파일만 사용할 수 있습니다.",true);setSaveState("이미지 압축 중…");try{imageDraft=await compressImage(file);imageRemoved=false;$("#questionPreview").src=imageDraft.dataUrl;$("#questionPreview").classList.remove("hidden");$("#pasteGuide").classList.add("hidden");$("#imageStatus").textContent=`${imageDraft.width}×${imageDraft.height} · ${Math.round(imageDraft.size/1024)}KB`;}catch{showToast("이미지를 읽지 못했습니다.",true);}finally{setSaveState();}}

function refreshExamOptions(keep=true){const exams=examCatalog(),existing=$("#existingExam").value,filter=$("#recordExamFilter").value,analysis=$("#analysisExam").value,keys=exams.map(x=>x.key);setExamOptions($("#existingExam"),exams,keep&&keys.includes(existing)?existing:"","새 시험 입력");setExamOptions($("#recordExamFilter"),exams,keys.includes(filter)?filter:"","전체 모의고사");setExamOptions($("#analysisExam"),exams,keys.includes(analysis)?analysis:"","모의고사 선택");syncExamInput();}
function syncExamInput(){const key=$("#existingExam").value,item=examCatalog().find(x=>x.key===key),locked=Boolean(item);if(item){const q=item.question;$("#newExamTitle").value=q.examTitle;$("#subject").value=q.subject;$("#examYear").value=q.year;$("#examRound").value=q.round;$("#examHint").textContent=`${examLabel(q)}에 문항이 추가됩니다.`;}else{if(!$("#questionId").value)$("#newExamTitle").value="";$("#examHint").textContent="새 시험의 과목·연도·시즌·회차를 입력하세요.";}["newExamTitle","subject","examYear","examRound"].forEach(id=>$("#"+id).disabled=locked);$("#newExamTitle").required=!locked;}
function syncDetailOptions(clear=false){const items=DETAIL_TYPES[$("#type").value]||[];$("#detailTypeList").innerHTML=items.map(item=>`<option value="${esc(item)}"></option>`).join("");if(clear)$("#detailType").value="";}
function resetForm(keepExam=""){imageDraft=null;imageRemoved=false;$("#recordForm").reset();$("#questionId").value="";$("#subject").value="통합과학";$("#examYear").value=String(CURRENT_YEAR);$("#examRound").value="1";$("#difficulty").value="중";$("#score").value="2";$("#questionNo").value="1";$("#detailType").value="";$("#memo").value="";$("#explanation").innerHTML="";$("#questionPreview").removeAttribute("src");$("#questionPreview").classList.add("hidden");$("#pasteGuide").classList.remove("hidden");$("#deleteBtn").classList.add("hidden");$("#imageStatus").textContent="선택 사항 · 붙여넣기 지원";syncDetailOptions();refreshExamOptions(false);if(keepExam&&examCatalog().some(x=>x.key===keepExam)){$("#existingExam").value=keepExam;syncExamInput();}}
async function saveQuestion(event){event.preventDefault();const selectedKey=$("#existingExam").value,selected=examCatalog().find(x=>x.key===selectedKey)?.question,examTitle=clean(selected?.examTitle||$("#newExamTitle").value),subject=selected?.subject||$("#subject").value,year=String(selected?.year||$("#examYear").value||CURRENT_YEAR),round=Number(selected?.round||$("#examRound").value)||1,id=$("#questionId").value||uid(),existing=state.questions.find(q=>q.id===id),explanationText=$("#explanation").innerText.trim();if(!examTitle)return showToast("시즌·모의고사 제목을 입력하세요.",true);if(!$("#answer").value)return showToast("정답을 선택하세요.",true);if(!explanationText)return showToast("해설을 입력하세요.",true);const question={id,examTitle,subject,year,season:examTitle,round,number:Number($("#questionNo").value),type:$("#type").value,detailType:clean($("#detailType").value),difficulty:$("#difficulty").value,score:Number($("#score").value),answer:$("#answer").value,explanationHtml:$("#explanation").innerHTML.trim(),explanationText,source:"",memo:$("#memo").value.trim(),problemPdfUrl:"",solutionPdfUrl:"",imageFileId:imageRemoved?"":existing?.imageFileId||"",imageFileName:imageRemoved?"":existing?.imageFileName||"",imageUrl:imageRemoved?"":existing?.imageUrl||"",hasLocalImage:Boolean(imageDraft)||Boolean(existing?.hasLocalImage&&!imageRemoved),removeImage:imageRemoved,createdAt:existing?.createdAt||now(),updatedAt:now()};const duplicate=state.questions.find(q=>q.id!==id&&examKey(q)===examKey(question)&&q.number===question.number);if(duplicate&&!confirm(`${examLabel(question)} ${question.number}번이 이미 있습니다. 그래도 저장할까요?`))return;if(imageDraft)await dbSet(id,imageDraft);const index=state.questions.findIndex(q=>q.id===id);if(index>=0)state.questions[index]=question;else state.questions.unshift(question);persist(true);renderAll();resetForm(examKey(question));showToast(index>=0?"문항을 수정했습니다.":"문항을 저장했습니다.");if(config().url&&config().key)await syncToServer("push",true);}
async function editQuestion(id){const q=state.questions.find(item=>item.id===id);if(!q)return;switchPage("record");$("#questionId").value=q.id;refreshExamOptions(false);$("#existingExam").value=examKey(q);syncExamInput();$("#type").value=q.type;syncDetailOptions();$("#detailType").value=q.detailType||"";$("#questionNo").value=q.number;$("#score").value=String(q.score);$("#difficulty").value=q.difficulty;$("#answer").value=q.answer;$("#memo").value=q.memo||"";$("#explanation").innerHTML=q.explanationHtml||esc(q.explanationText).replace(/\n/g,"<br>");const draft=await dbGet(q.id);imageDraft=draft||null;imageRemoved=false;const url=draft?.dataUrl||q.imageUrl;if(url){$("#questionPreview").src=url;$("#questionPreview").classList.remove("hidden");$("#pasteGuide").classList.add("hidden");$("#imageStatus").textContent=draft?"동기화할 새 이미지":"Drive 이미지";}else{$("#questionPreview").classList.add("hidden");$("#pasteGuide").classList.remove("hidden");}$("#deleteBtn").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});}
async function deleteCurrent(){const id=$("#questionId").value,q=state.questions.find(item=>item.id===id);if(!q||!confirm(`${examLabel(q)} ${q.number}번을 삭제할까요?`))return;state.questions=state.questions.filter(item=>item.id!==id);await dbDelete(id);persist(true);resetForm();renderAll();showToast("문항을 삭제했습니다.");if(config().url&&config().key)await syncToServer("push",true);}

function renderRecordList(){const filter=$("#recordExamFilter").value,questions=state.questions.filter(q=>!filter||examKey(q)===filter).sort((a,b)=>examLabel(a).localeCompare(examLabel(b),"ko",{numeric:true})||a.number-b.number),list=$("#recordList");$("#recordCount").textContent=questions.length;if(!questions.length){list.innerHTML='<div class="empty-state"><strong>아직 저장된 문항이 없습니다.</strong><p>위 입력란에서 첫 문항을 저장하면 이곳에 시험별로 정리됩니다.</p></div>';return;}list.innerHTML=questions.map(q=>`<article class="record-row"><div class="exam">${esc(examLabel(q))}</div><div class="type">${esc(q.type)}${q.detailType?`<small>${esc(q.detailType)}</small>`:""}</div><span class="pill">${q.number}번</span><span class="pill score">${format(q.score)}점</span><span class="difficulty ${difficultyClass(q.difficulty)}">${esc(q.difficulty)}</span><span class="pill answer">${esc(q.answer)}</span><div>${q.imageUrl||q.hasLocalImage?`<img class="record-thumb" src="${esc(q.imageUrl)}" alt="문항 이미지" data-view="${esc(q.id)}">`:'<span class="pill">이미지 없음</span>'}</div><div class="row-actions"><button data-view="${esc(q.id)}">보기</button><button data-edit="${esc(q.id)}">수정</button><button class="danger" data-delete="${esc(q.id)}">삭제</button></div></article>`).join("");hydrateDraftThumbs();}
async function hydrateDraftThumbs(){for(const q of state.questions){const draft=await dbGet(q.id);if(!draft?.dataUrl)continue;const image=$(`[data-view="${CSS.escape(q.id)}"].record-thumb`);if(image)image.src=draft.dataUrl;}}

function renderExamChecks(){const catalog=examCatalog(),keys=catalog.map(x=>x.key),subject=$("#compareSubjectFilter")?.value||"전체",exams=subject==="전체"?catalog:catalog.filter(exam=>exam.question.subject===subject);state.selectedExams=state.selectedExams.filter(key=>keys.includes(key)).slice(0,8);$("#compareCount").textContent=state.selectedExams.length;$("#examChecks").innerHTML=exams.length?exams.map(exam=>`<label class="exam-check"><input type="checkbox" value="${esc(exam.key)}" ${state.selectedExams.includes(exam.key)?"checked":""}>${esc(exam.label)}</label>`).join(""):`<div class="empty-state">${subject==="전체"?"저장된 모의고사가 없습니다.":esc(subject)+" 모의고사가 없습니다."}</div>`;}
function toggleExam(key,checked){if(checked&&state.selectedExams.length>=8){showToast("최대 8개까지 비교할 수 있습니다.",true);renderExamChecks();return;}state.selectedExams=checked?[...state.selectedExams,key]:state.selectedExams.filter(item=>item!==key);persist(false);renderExamChecks();renderCompare();}
function renderCompare(){const exams=state.selectedExams,catalog=new Map(examCatalog().map(x=>[x.key,x.label]));$$('[data-record-compare-mode]').forEach(button=>button.classList.toggle("active",button.dataset.recordCompareMode===recordCompareMode));$("#compareTableTitle").textContent=recordCompareMode==="number"?"번호별 비교표":"유형별 비교표";if(!exams.length){$("#compareEmpty").classList.remove("hidden");$("#compareScroll").classList.add("hidden");return;}$("#compareEmpty").classList.add("hidden");$("#compareScroll").classList.remove("hidden");const questions=state.questions.filter(q=>exams.includes(examKey(q))),heading=key=>esc(catalog.get(key)||key);if(recordCompareMode==="number"){const numbers=[...new Set(questions.map(q=>q.number))].sort((a,b)=>a-b);$("#compareTable").innerHTML=`<thead><tr><th>번호</th>${exams.map(key=>`<th>${heading(key)}</th>`).join("")}</tr></thead><tbody>${numbers.map(number=>`<tr><td><b>${number}번</b></td>${exams.map(key=>{const q=questions.find(item=>examKey(item)===key&&item.number===number);return`<td><div class="compare-cell-stack">${q?comparePreviewCard(q):'<div class="compare-missing">해당 문항 없음</div>'}</div></td>`;}).join("")}</tr>`).join("")}</tbody>`;}else{const types=[...new Set(questions.map(q=>q.type))].sort((a,b)=>quickTypeOrder(a)-quickTypeOrder(b)||a.localeCompare(b,"ko"));$("#compareTable").innerHTML=`<thead><tr><th>유형</th>${exams.map(key=>`<th>${heading(key)}</th>`).join("")}</tr></thead><tbody>${types.map(type=>{const rows=questions.filter(q=>q.type===type);return`<tr><td>${esc(type)}<span class="type-total">총 ${rows.length}문항</span></td>${exams.map(key=>`<td><div class="compare-cell-stack">${rows.filter(q=>examKey(q)===key).sort((a,b)=>a.number-b.number).map(q=>comparePreviewCard(q)).join("")||'<div class="compare-missing">해당 문항 없음</div>'}</div></td>`).join("")}</tr>`}).join("")}`;}hydrateCompareDrafts();}
function comparePreviewCard(q){const hasImage=q.imageUrl||q.hasLocalImage;return`<article class="compare-preview-card ${difficultyClass(q.difficulty)}"><button type="button" class="compare-image-button" data-view="${esc(q.id)}">${hasImage?`<img class="compare-preview-image ${q.imageUrl?"":"hidden"}" data-compare-image="${esc(q.id)}" src="${esc(q.imageUrl)}" alt="${esc(q.examTitle)} ${q.number}번"><span class="compare-image-placeholder ${q.imageUrl?"hidden":""}" data-compare-placeholder="${esc(q.id)}">이미지 불러오는 중…</span>`:'<span class="compare-image-placeholder">이미지 없음</span>'}</button><div class="compare-preview-meta"><strong>${q.number}번 · ${format(q.score)}점 · ${esc(q.answer)}</strong><span class="difficulty ${difficultyClass(q.difficulty)}">${esc(q.difficulty)}</span></div><p class="compare-preview-type">${esc(q.type)}${q.detailType?`<small>${esc(q.detailType)}</small>`:""}</p><textarea class="compare-memo" data-compare-memo="${esc(q.id)}" rows="3" placeholder="이 문항에 대한 비교 메모">${esc(q.memo||"")}</textarea></article>`;}
async function copyCompareTable(){const exams=state.selectedExams,catalog=new Map(examCatalog().map(x=>[x.key,x.label]));if(!exams.length)return showToast("비교할 모의고사를 먼저 선택하세요.",true);const selected=state.questions.filter(q=>exams.includes(examKey(q))),keys=recordCompareMode==="number"?[...new Set(selected.map(q=>q.number))].sort((a,b)=>a-b):[...new Set(selected.map(q=>q.type))].sort((a,b)=>quickTypeOrder(a)-quickTypeOrder(b)||a.localeCompare(b,"ko"));const find=(exam,key)=>selected.filter(q=>examKey(q)===exam&&(recordCompareMode==="number"?q.number===key:q.type===key)).sort((a,b)=>a.number-b.number);const cache={};for(const q of selected){const draft=await dbGet(q.id);cache[q.id]=draft?.dataUrl||q.imageUrl||"";}const cell=items=>items.map(q=>`<div style="text-align:center;margin:0 0 10px;page-break-inside:avoid">${cache[q.id]?`<img src="${cache[q.id]}" width="151" style="width:40mm;height:auto;max-width:none"><br>`:""}<b>${q.number}번</b> · ${format(q.score)}점 · 정답 ${esc(q.answer)}<br>${esc(q.detailType||q.type)}${q.memo?`<br><span style="color:#555">${esc(q.memo)}</span>`:""}</div>`).join("");const border='border:1px solid #222;padding:7px;vertical-align:top',labels=exams.map(key=>catalog.get(key)||key);const html=`<table style="border-collapse:collapse;font-family:'Malgun Gothic',sans-serif;font-size:9pt"><thead><tr><th style="${border};background:#eef2f5">${recordCompareMode==="number"?"번호":"유형"}</th>${labels.map(label=>`<th style="${border};background:#eef2f5">${esc(label)}</th>`).join("")}</tr></thead><tbody>${keys.map(key=>`<tr><th style="${border};min-width:110px">${recordCompareMode==="number"?key+"번":esc(key)}</th>${exams.map(exam=>`<td style="${border};min-width:230px">${cell(find(exam,key))}</td>`).join("")}</tr>`).join("")}</tbody></table>`;const plain=[[recordCompareMode==="number"?"번호":"유형",...labels].join("\t"),...keys.map(key=>[key,...exams.map(exam=>find(exam,key).map(q=>`${q.number}번 ${q.detailType||q.type} ${format(q.score)}점`).join(" / "))].join("\t"))].join("\n");try{if(window.ClipboardItem&&navigator.clipboard?.write)await navigator.clipboard.write([new ClipboardItem({"text/html":new Blob([html],{type:"text/html"}),"text/plain":new Blob([plain],{type:"text/plain"})})]);else await navigator.clipboard.writeText(plain);showToast("한글에 붙여넣을 비교표를 복사했습니다.");}catch(error){console.error(error);showToast("표를 복사하지 못했습니다.",true);}}
async function hydrateCompareDrafts(){for(const q of state.questions.filter(item=>item.hasLocalImage&&!item.imageUrl)){const draft=await dbGet(q.id);if(!draft?.dataUrl)continue;const image=$(`[data-compare-image="${CSS.escape(q.id)}"]`),placeholder=$(`[data-compare-placeholder="${CSS.escape(q.id)}"]`);if(image){image.src=draft.dataUrl;image.classList.remove("hidden");}placeholder?.classList.add("hidden");}}
async function saveCompareMemo(id,value){const question=state.questions.find(item=>item.id===id);if(!question||question.memo===value)return;question.memo=value;question.updatedAt=now();persist(true);showToast("메모를 저장했습니다.");if(config().url&&config().key)await syncToServer("push",true);}

function renderAnalysis(){const exam=$("#analysisExam").value,questions=state.questions.filter(q=>examKey(q)===exam).sort((a,b)=>a.number-b.number);if(!exam||!questions.length){$("#analysisEmpty").classList.remove("hidden");$("#analysisContent").classList.add("hidden");return;}$("#analysisEmpty").classList.add("hidden");$("#analysisContent").classList.remove("hidden");const totalScore=questions.reduce((sum,q)=>sum+q.score,0),typeCount=new Set(questions.map(q=>q.type)).size;$("#metricGrid").innerHTML=[["시험",examLabel(questions[0])],["문항 수",`${questions.length}문항`],["총 배점",`${format(totalScore)}점`],["유형 수",`${typeCount}개`],["이미지",`${questions.filter(q=>q.imageUrl||q.hasLocalImage).length}문항`]].map(([label,value])=>`<div class="metric"><span>${label}</span><strong>${esc(value)}</strong></div>`).join("");renderAnswerCounts($("#answerCounts"),questions.map(q=>answerNumber(q.answer)));renderBars($("#scoreCounts"),[1.5,2,2.5,3].map(value=>({label:`${value}점`,count:questions.filter(q=>q.score===value).length})));renderBars($("#difficultyCounts"),DIFFICULTIES.map(value=>({label:value,count:questions.filter(q=>q.difficulty===value).length})));$("#answerSequence").innerHTML=questions.map(q=>`<span class="sequence-chip"><span>${q.number}</span><b>${esc(q.answer)}</b></span>`).join("");const issues=answerIssues(questions.map(q=>({number:q.number,answer:answerNumber(q.answer)})));$("#analysisAlert").className=`analysis-alert${issues.length?" warn":""}`;$("#analysisAlert").textContent=issues.length?issues.join(" · "):"정답 수와 연속 배치에서 두드러지는 쏠림이 없습니다.";const grouped=groupBy(questions,q=>q.type);$("#typeAnalysis").innerHTML=[...grouped.entries()].sort((a,b)=>TYPES.indexOf(a[0])-TYPES.indexOf(b[0])).map(([type,items])=>`<div class="type-analysis-row"><span>${esc(type)}</span><b>${items.map(q=>`${q.number}번(${format(q.score)})`).join(", ")}</b></div>`).join("");}
function renderAnswerCounts(target,answers){const counts=[1,2,3,4,5].map(value=>answers.filter(answer=>answer===value).length),max=Math.max(1,...counts);target.innerHTML=counts.map((count,index)=>`<div class="answer-count" style="--height:${count/max*100}%"><span>${ANSWERS[index+1]}</span><b>${count}</b></div>`).join("");}
function renderBars(target,data){const max=Math.max(1,...data.map(item=>item.count));target.innerHTML=data.map(item=>`<div class="metric-row"><span>${item.label}</span><div class="bar-track"><div class="bar-fill" style="width:${item.count/max*100}%"></div></div><b>${item.count}</b></div>`).join("");}
function answerIssues(rows){const answers=rows.map(row=>row.answer).filter(Boolean),counts=[1,2,3,4,5].map(value=>answers.filter(answer=>answer===value).length),issues=[];if(answers.length){const gap=Math.max(...counts)-Math.min(...counts);if(gap>=3)issues.push(`답 번호 개수 차이가 ${gap}개입니다`);}let run=1,maxRun=1;for(let i=1;i<rows.length;i++){run=rows[i].answer&&rows[i].answer===rows[i-1].answer?run+1:1;maxRun=Math.max(maxRun,run);}if(maxRun>=3)issues.push(`같은 답이 최대 ${maxRun}회 연속됩니다`);return issues;}

function importedType(value){const key=String(value||"").replace(/[\s,，·.\-–—]/g,"");return TYPES.find(type=>type.replace(/[\s,，·.\-–—]/g,"")===key)||String(value||"").trim();}
function quickScoreCount(rows,score){return rows.filter(row=>Number(row.score)===score).length;}
function quickAnswer(row){return row?.answerSymbol||ANSWERS[Number(row?.answer)]||"—";}
function quickTypeOrder(type){const index=TYPES.indexOf(type);return index<0?TYPES.length:index;}
function quickAnswerRows(rows){const sorted=[...rows].sort((a,b)=>a.number-b.number),groups=[];for(let index=0;index<sorted.length;index+=5)groups.push(sorted.slice(index,index+5));return groups;}
function quickAnswerTableMarkup(rows,copy=false){const style=copy?' style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:10pt"':"",cell=copy?' style="border:1px solid #222;padding:2px 8px;text-align:center"':"";return`<table${style}><tbody>${quickAnswerRows(rows).map(group=>`<tr>${group.map(row=>`<td${cell}>${row.number}</td><td${cell}>${quickAnswer(row)}</td>`).join("")}</tr>`).join("")}</tbody></table>`;}
async function copyQuickAnswerTable(index){const exam=quickExams[index];if(!exam)return;const rows=quickAnswerRows(exam.rows),plain=rows.map(group=>group.flatMap(row=>[row.number,quickAnswer(row)]).join("\t")).join("\n"),html=quickAnswerTableMarkup(exam.rows,true);try{if(window.ClipboardItem&&navigator.clipboard?.write)await navigator.clipboard.write([new ClipboardItem({"text/html":new Blob([html],{type:"text/html"}),"text/plain":new Blob([plain],{type:"text/plain"})})]);else await navigator.clipboard.writeText(plain);showToast(`${exam.name} 답안표를 복사했습니다.`);}catch(error){console.error(error);showToast("표를 복사하지 못했습니다.",true);}}
function renderQuickScoreCounts(target,rows){target.innerHTML=[1.5,2,2.5].map(score=>`<div class="quick-score-count"><span>${format(score)}점</span><strong>${quickScoreCount(rows,score)}</strong><small>문항</small></div>`).join("");}
function quickExamCell(row){return row?`<div class="quick-compare-cell"><strong>${quickAnswer(row)}</strong><span>${format(row.score)}점</span><p>${esc(row.type)}</p></div>`:`<div class="quick-compare-cell empty">—</div>`;}
function renderQuickNumberCompare(){const [first,second]=quickExams,numbers=[...new Set([...first.rows,...second.rows].map(row=>row.number))].sort((a,b)=>a-b),find=(exam,number)=>exam.rows.find(row=>row.number===number);$("#quickCompareTable").innerHTML=`<thead><tr><th>번호</th><th>${esc(first.name)}</th><th>${esc(second.name)}</th></tr></thead><tbody>${numbers.map(number=>`<tr><td><b>${String(number).padStart(2,"0")}번</b></td><td>${quickExamCell(find(first,number))}</td><td>${quickExamCell(find(second,number))}</td></tr>`).join("")}</tbody>`;}
function renderQuickTypeCompare(){const [first,second]=quickExams,types=[...new Set([...first.rows,...second.rows].map(row=>row.type))].sort((a,b)=>quickTypeOrder(a)-quickTypeOrder(b)||a.localeCompare(b,"ko")),items=(exam,type)=>exam.rows.filter(row=>row.type===type).sort((a,b)=>a.number-b.number);$("#quickCompareTable").innerHTML=`<thead><tr><th>유형</th><th>${esc(first.name)}</th><th>${esc(second.name)}</th></tr></thead><tbody>${types.map(type=>`<tr><td><b>${esc(type)}</b></td>${[first,second].map(exam=>{const rows=items(exam,type);return`<td><div class="quick-type-items">${rows.length?rows.map(row=>`<span><b>${String(row.number).padStart(2,"0")}번</b> ${quickAnswer(row)} · ${format(row.score)}점</span>`).join(""):"<span class=\"empty\">해당 문항 없음</span>"}</div></td>`;}).join("")}</tr>`).join("")}</tbody>`;}
function renderQuickCompare(){const [first,second]=quickExams;$("#quickCompareAnswerTables").innerHTML=quickExams.map((exam,index)=>`<section><div><strong>${esc(exam.name)}</strong><button type="button" class="button ghost" data-copy-quick="${index}">표 복사</button></div><div class="quick-answer-copy">${quickAnswerTableMarkup(exam.rows)}</div></section>`).join("");$("#quickScoreCompare").innerHTML=`<table><thead><tr><th>배점</th><th>${esc(first.name)}</th><th>${esc(second.name)}</th><th>차이</th></tr></thead><tbody>${[1.5,2,2.5].map(score=>{const a=quickScoreCount(first.rows,score),b=quickScoreCount(second.rows,score),difference=b-a;return`<tr><th>${format(score)}점</th><td>${a}문항</td><td>${b}문항</td><td class="${difference===0?"same":difference>0?"plus":"minus"}">${difference>0?"+":""}${difference}</td></tr>`;}).join("")}</tbody></table>`;$$('[data-quick-mode]').forEach(button=>button.classList.toggle("active",button.dataset.quickMode===quickCompareMode));if(quickCompareMode==="type")renderQuickTypeCompare();else renderQuickNumberCompare();}
function renderQuickSingle(exam){const rows=exam.rows,totalScore=rows.reduce((sum,row)=>sum+Number(row.score||0),0),typeCount=new Set(rows.map(row=>row.type)).size;$("#quickHwpMetrics").innerHTML=[["파일",exam.name],["문항 수",`${rows.length}문항`],["총 배점",`${format(totalScore)}점`],["유형 수",`${typeCount}개`]].map(([label,value],index)=>`<div class="metric ${index===0?"file-metric":""}"><span>${label}</span><strong>${esc(value)}</strong></div>`).join("");renderQuickScoreCounts($("#quickSingleScoreCounts"),rows);$("#quickSingleAnswerTable").innerHTML=quickAnswerTableMarkup(rows);$("#quickQuestionBoard").innerHTML=rows.map(row=>`<article class="quick-question-card"><div><strong>${String(row.number).padStart(2,"0")}번</strong><span>${quickAnswer(row)}</span></div><p>${esc(row.type)}</p><small>${format(row.score)}점</small></article>`).join("");$("#quickQuestionTable").innerHTML=`<thead><tr><th>번호</th><th>정답</th><th>배점</th><th>유형</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${String(row.number).padStart(2,"0")}번</td><td class="quick-table-answer">${quickAnswer(row)}</td><td>${format(row.score)}점</td><td>${esc(row.type)}</td></tr>`).join("")}</tbody>`;}
function renderQuick(){const empty=$("#quickHwpEmpty"),results=$("#quickHwpResults"),clear=$("#quickClear"),chips=$("#quickExamChips"),status=$("#quickHwpStatus");status.textContent=`모의고사 ${quickExams.length}/2 · ${quickExams.length===2?"번호별·유형별 비교 준비됨":"‘01번 답 ③-유형(1.5)’ 형식을 읽습니다."}`;chips.classList.toggle("hidden",!quickExams.length);chips.innerHTML=quickExams.map((exam,index)=>`<span><b>${index+1}</b>${esc(exam.name)} <small>${exam.rows.length}문항</small><button type="button" data-remove-quick="${index}" aria-label="${esc(exam.name)} 삭제">×</button></span>`).join("");if(!quickExams.length){empty.classList.remove("hidden");results.classList.add("hidden");clear.classList.add("hidden");return;}empty.classList.add("hidden");results.classList.remove("hidden");clear.classList.remove("hidden");const comparing=quickExams.length===2;$("#quickSingleResults").classList.toggle("hidden",comparing);$("#quickCompareResults").classList.toggle("hidden",!comparing);if(comparing)renderQuickCompare();else renderQuickSingle(quickExams[0]);}
function clearQuickHwp(){quickExams=[];quickCompareMode="number";renderQuick();}
function removeQuickExam(index){quickExams.splice(index,1);renderQuick();}
async function importQuickHwp(file){const status=$("#quickHwpStatus"),input=$("#quickHwpInput");if(!file)return;if(!/\.hwp$/i.test(file.name)){showToast(".hwp 파일을 선택하세요.",true);return;}const name=file.name.replace(/\.hwp$/i,"");const existing=quickExams.findIndex(exam=>exam.name===name);if(existing<0&&quickExams.length>=2){showToast("최대 2개입니다. 기존 파일 하나를 지운 뒤 추가하세요.",true);input.value="";return;}status.textContent=`${file.name} 읽는 중…`;input.disabled=true;try{const rows=(await window.HwpQuickImport.parse(file)).map(row=>({...row,type:importedType(row.type)}));if(!rows.length)throw new Error("문항 머리말을 찾지 못했습니다.");const exam={name,rows};if(existing>=0)quickExams[existing]=exam;else quickExams.push(exam);renderQuick();showToast(`${name} · ${rows.length}문항을 읽었습니다.`);}catch(error){console.error(error);status.textContent=`분석 실패 · ${error.message}`;showToast(error.message,true);}finally{input.disabled=false;input.value="";}}

function groupBy(items,keyFn){const map=new Map();items.forEach(item=>{const key=keyFn(item);if(!map.has(key))map.set(key,[]);map.get(key).push(item)});return map;}
async function openDetail(id){const q=state.questions.find(item=>item.id===id);if(!q)return;detailId=id;$("#detailTitle").textContent=`${examLabel(q)} · ${q.number}번`;$("#detailMeta").textContent=`${q.type}${q.detailType?` · ${q.detailType}`:""} · ${format(q.score)}점 · ${q.difficulty} · 정답 ${q.answer}`;$("#detailExplanation").innerHTML=q.explanationHtml||esc(q.explanationText).replace(/\n/g,"<br>");const draft=await dbGet(id),url=draft?.dataUrl||q.imageUrl;if(url){$("#detailImage").src=url;$("#detailImageWrap").classList.remove("hidden");}else{$("#detailImageWrap").classList.add("hidden");}$("#detailDialog").showModal();}
function switchPage(page){currentPage=page;$$('.page').forEach(element=>element.classList.toggle("active",element.id===`${page}Page`));$$('.bottom-nav button').forEach(button=>button.classList.toggle("active",button.dataset.page===page));if(page==="compare"){renderExamChecks();renderCompare();}if(page==="analysis")renderAnalysis();if(page==="quick")renderQuick();}
function renderAll(){refreshExamOptions(true);renderRecordList();renderExamChecks();renderCompare();renderAnalysis();if(currentPage==="quick")renderQuick();}

async function fetchSyncResult(url,options){let lastError;for(let attempt=0;attempt<20;attempt++){try{const response=await fetch(url,options),data=await response.json();if(data.code!=="SYNC_BUSY")return data;lastError=new Error(data.message||"다른 동기화를 처리하고 있습니다.");}catch(error){lastError=error;if(attempt>=4)throw error;}if(attempt<19){setSaveState("다른 동기화 완료 대기 중…");await delay(2000);}}throw lastError||new Error("동기화 재시도 실패");}
function syncToServer(mode="pull",silent=false){if(syncInFlight){if(mode==="push")syncQueuedPush=true;return syncInFlight;}syncInFlight=performSyncToServer(mode,silent).finally(()=>{syncInFlight=null;if(syncQueuedPush){syncQueuedPush=false;if(state.dirty)syncToServer("push",true);}});return syncInFlight;}
async function performSyncToServer(mode="pull",silent=false){const cfg=config();if(!cfg.url||!cfg.key){$("#settingsDialog").showModal();if(!silent)showToast("먼저 연결을 설정하세요.");return;}const button=$("#syncBtn");setBusy(button,true,mode==="pull"?"불러오는 중…":"동기화 중…");setSaveState("시트 연결 중…");try{if(mode==="pull"){if(state.dirty&&!confirm("동기화하지 않은 변경을 시트 데이터로 덮어쓸까요?"))return;const url=new URL(cfg.url);url.searchParams.set("action","load");url.searchParams.set("key",cfg.key);url.searchParams.set("_",Date.now());const data=await fetchSyncResult(url);if(!data.ok)throw new Error(data.message||"불러오기 실패");const localQuick=state.quick,selected=state.selectedExams;state={questions:(data.questions||[]).map(normalizeQuestion),seasons:data.seasons||[],quick:localQuick,selectedExams:selected,updatedAt:data.syncedAt||now(),dirty:false};localStorage.setItem(STORE_KEY,JSON.stringify(state));renderAll();showToast(`${state.questions.length}문항을 불러왔습니다.`);}else{const sentQuestions=state.questions.map(q=>({...q})),sentMap=new Map(sentQuestions.map(q=>[q.id,q])),revisionToken=sentQuestions.map(q=>`${q.id}:${q.updatedAt}`).join("|"),drafts=await collectDrafts(),body=new URLSearchParams({action:"sync",key:cfg.key,payload:JSON.stringify({questions:sentQuestions,imageDrafts:drafts})}),data=await fetchSyncResult(cfg.url,{method:"POST",body});if(!data.ok)throw new Error(data.message||"동기화 실패");const remoteMap=new Map((data.questions||[]).map(q=>[q.id,normalizeQuestion(q)])),currentToken=state.questions.map(q=>`${q.id}:${q.updatedAt}`).join("|"),changedDuringSync=currentToken!==revisionToken;if(changedDuringSync){state.questions=state.questions.map(local=>{const remote=remoteMap.get(local.id),sent=sentMap.get(local.id);if(!remote||!sent)return local;if(local.updatedAt===sent.updatedAt)return remote;return{...local,imageFileId:remote.imageFileId||local.imageFileId,imageFileName:remote.imageFileName||local.imageFileName,imageUrl:remote.imageUrl||local.imageUrl};});state.dirty=true;}else{state.questions=(data.questions||state.questions).map(normalizeQuestion);state.updatedAt=data.syncedAt||now();state.dirty=false;}localStorage.setItem(STORE_KEY,JSON.stringify(state));for(const id of Object.keys(drafts)){const current=await dbGet(id);if(current?.dataUrl===drafts[id]?.dataUrl)await dbDelete(id);}if(!changedDuringSync)imageDraft=null;renderAll();showToast(changedDuringSync?"새 변경 사항을 이어서 동기화합니다.":"시트와 Drive에 동기화했습니다.");}}catch(error){console.error(error);showToast(`연결 실패: ${error.message}`,true);setSaveState("연결 확인 필요");}finally{setBusy(button,false);setSaveState();}}
async function verifySettings(){const button=$("#saveSettingsBtn"),url=$("#scriptUrl").value.trim(),key=$("#syncKey").value.trim();if(!/^https:\/\/script\.google\.com\//.test(url)||!key)return showToast("배포 URL과 동기화 키를 확인하세요.",true);localStorage.setItem(CONFIG_KEY,JSON.stringify({url,key}));setBusy(button,true,"확인 중…");try{const test=new URL(url);test.searchParams.set("action","ping");test.searchParams.set("key",key);const data=await(await fetch(test)).json();if(!data.ok)throw new Error(data.message||"인증 실패");$("#settingsDialog").close();showToast("연결되었습니다.");await syncToServer("pull",true);}catch(error){showToast(`연결 실패: ${error.message}`,true);}finally{setBusy(button,false);}}

function bind(){
  $$('.bottom-nav button').forEach(button=>button.addEventListener("click",()=>switchPage(button.dataset.page)));
  $("#recordForm").addEventListener("submit",saveQuestion);$("#existingExam").addEventListener("change",syncExamInput);$("#type").addEventListener("change",()=>syncDetailOptions(true));$("#newBtn").addEventListener("click",()=>resetForm());$("#deleteBtn").addEventListener("click",deleteCurrent);$("#recordExamFilter").addEventListener("change",renderRecordList);
  $("#imageInput").addEventListener("change",event=>acceptImage(event.target.files[0]));$("#clearImageBtn").addEventListener("click",()=>{imageDraft=null;imageRemoved=true;$("#questionPreview").removeAttribute("src");$("#questionPreview").classList.add("hidden");$("#pasteGuide").classList.remove("hidden");$("#imageStatus").textContent="이미지 비움";});const zone=$("#pasteZone");zone.addEventListener("paste",event=>{const file=[...event.clipboardData.items].find(item=>item.type.startsWith("image/"))?.getAsFile();if(file){event.preventDefault();acceptImage(file)}});["dragenter","dragover"].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.add("dragover")}));["dragleave","drop"].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.remove("dragover")}));zone.addEventListener("drop",event=>acceptImage(event.dataTransfer.files[0]));
  $("#explanation").addEventListener("paste",event=>{event.preventDefault();insertHtmlAtCursor(sanitizePastedHtml(event.clipboardData.getData("text/html"),event.clipboardData.getData("text/plain")))});
  $("#recordList").addEventListener("click",event=>{const view=event.target.closest("[data-view]"),edit=event.target.closest("[data-edit]"),remove=event.target.closest("[data-delete]");if(view)openDetail(view.dataset.view);if(edit)editQuestion(edit.dataset.edit);if(remove){const q=state.questions.find(item=>item.id===remove.dataset.delete);if(q&&confirm(`${examLabel(q)} ${q.number}번을 삭제할까요?`)){state.questions=state.questions.filter(item=>item.id!==q.id);dbDelete(q.id);persist(true);renderAll();}}});
  $("#examChecks").addEventListener("change",event=>{if(event.target.type==="checkbox")toggleExam(event.target.value,event.target.checked)});$("#compareSubjectFilter").addEventListener("change",renderExamChecks);$("#comparePage").addEventListener("click",event=>{const mode=event.target.closest("[data-record-compare-mode]");if(mode){recordCompareMode=mode.dataset.recordCompareMode;renderCompare();}});$("#copyCompareBtn").addEventListener("click",copyCompareTable);$("#compareTable").addEventListener("click",event=>{const target=event.target.closest("[data-view]");if(target)openDetail(target.dataset.view)});$("#compareTable").addEventListener("change",event=>{if(event.target.matches("[data-compare-memo]"))saveCompareMemo(event.target.dataset.compareMemo,event.target.value)});$("#analysisExam").addEventListener("change",renderAnalysis);
  $("#quickHwpInput").addEventListener("change",event=>importQuickHwp(event.target.files[0]));$("#quickClear").addEventListener("click",clearQuickHwp);const hwpZone=$("#hwpImportZone");["dragenter","dragover"].forEach(name=>hwpZone.addEventListener(name,event=>{event.preventDefault();hwpZone.classList.add("dragover")}));["dragleave","drop"].forEach(name=>hwpZone.addEventListener(name,event=>{event.preventDefault();hwpZone.classList.remove("dragover")}));hwpZone.addEventListener("drop",event=>importQuickHwp([...event.dataTransfer.files].find(file=>/\.hwp$/i.test(file.name))||event.dataTransfer.files[0]));$("#quickPage").addEventListener("click",event=>{const remove=event.target.closest("[data-remove-quick]"),mode=event.target.closest("[data-quick-mode]"),copy=event.target.closest("[data-copy-quick]");if(remove)removeQuickExam(Number(remove.dataset.removeQuick));if(mode){quickCompareMode=mode.dataset.quickMode;renderQuickCompare();}if(copy)copyQuickAnswerTable(Number(copy.dataset.copyQuick));});
  $("#detailEditBtn").addEventListener("click",()=>{$("#detailDialog").close();editQuestion(detailId)});$$('[data-close]').forEach(button=>button.addEventListener("click",()=>$("#"+button.dataset.close).close()));
  $("#settingsBtn").addEventListener("click",()=>{const cfg=config();$("#scriptUrl").value=cfg.url||"";$("#syncKey").value=cfg.key||"";$("#settingsDialog").showModal()});$("#saveSettingsBtn").addEventListener("click",verifySettings);$("#syncBtn").addEventListener("click",()=>syncToServer(state.dirty?"push":"pull"));
}
function init(){options($("#type"),TYPES,TYPES[0]);syncDetailOptions();bind();refreshExamOptions(false);renderAll();setSaveState();const cfg=config();if(cfg.url&&cfg.key&&!state.dirty)syncToServer("pull",true);}
init();
